<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universidad [
<!ELEMENT universidad (alumnos, profesores, asignaturas)>
<!ELEMENT alumnos (alumno*)>
<!ELEMENT alumno (DNI,pasaporte, pais?, nombre, apellido1, apellido2, fechaNacimiento, infoExtra?)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT pasaporte (pais)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT infoExtra (direccionPostal?, telefonos*, cuentasCorreos*)>
<!ELEMENT direccionPostal (#PCDATA)>
<!ELEMENT telefonos (tel+)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT cuentasCorreos (cuentaGmail+)>
<!ELEMENT cuentaGmail (#PCDATA)>
<!ELEMENT profesores (profesor)>
<!ELEMENT profesor (DNI, nombre, apellido1, apellido2, fechaNacimiento,infoExtra?,despacho,horarioTuto,asignaturasImpartidas)>
<!ELEMENT despacho (#PCDATA)>
<!ELEMENT horarioTuto (#PCDATA)>
<!ELEMENT asignaturasImpartidas (#PCDATA)>
<!ELEMENT asignaturas (nota, codigo, creditos, carrera, curso?)>
<!ELEMENT nota (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT creditos (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
]>

<universidad>
    <alumnos>
        <alumno>
            <DNI>65544488G</DNI>
            <pasaporte>
                <pais></pais>
            </pasaporte>
            <nombre>Alejandro</nombre>
            <apellido1>Jiménez</apellido1>
            <apellido2>Pérez</apellido2>
            <fechaNacimiento>5/2/1995</fechaNacimiento>
            <infoExtra>
                <direccionPostal></direccionPostal>
                <telefonos>
                    <tel></tel>
                </telefonos>
                <cuentasCorreos>
                    <cuentaGmail></cuentaGmail>
                </cuentasCorreos>
            </infoExtra>
        </alumno>
    </alumnos>
    <profesores>
        <profesor>
            <DNI>88889451I</DNI>
            <nombre>Juan</nombre>
            <apellido1>Gomez</apellido1>
            <apellido2>Trujillo</apellido2>
            <fechaNacimiento>8/4/2005</fechaNacimiento>
            <infoExtra>
                <direccionPostal>11596</direccionPostal>
                <telefonos>
                    <tel>888999777</tel>
                </telefonos>
                <cuentasCorreos>
                    <cuentaGmail>Juangt@gmail.com</cuentaGmail>
                </cuentasCorreos>
            </infoExtra>
            <despacho>8</despacho>
            <horarioTuto>15:00</horarioTuto>
            <asignaturasImpartidas>Matematicas</asignaturasImpartidas>
        </profesor>
    </profesores>
    <asignaturas>
        <nota>Sobresaliente</nota>
        <codigo>4</codigo>
        <creditos>74</creditos>
        <carrera>Ingieneria Informática</carrera>
        <curso>1</curso>
    </asignaturas>
</universidad>